version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - CI=true
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    environment:
      - CI=true
