version: "3"
services:
  mongodb:
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:1.0.0-alpha
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - mongodb
  client:
    # command: ["tail", "-f", "/dev/null"] # debugging
    command: ["/bin/sh", "-c", "echo 'Starting...' && npm install && npm start"]
    environment:
      - CI=true # react-scripts hack - https://github.com/facebook/create-react-app/issues/8688
      - BROWSER=none
      - PORT=3000
    ports:
      - "3000:3000"
  api:
    command:
      ["/bin/sh", "-c", "echo 'Starting...' && npm install && node index.js"]
