version: "3"
services:
  api:
    image: yvantcoop/ooi-backend:latest
    volumes:
      - "./.env:/app/.env:ro"
      - "./rds-combined-ca-bundle.pem:/etc/ssl/certs/rds-combined-ca-bundle.pem"
      - "/var/log/eb-docker/containers/api:/usr/src/app/log"
  client:
    image: yvantcoop/ooi-client:latest
    ports:
      - "80:80"
    volumes:
      - "/var/log/eb-docker/containers/client:/var/log/nginx"
    links:
      - api
