name: main
on: [push]
env:
  CI_COMMIT: ${{ GITHUB_SHA }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # SSH debugging
      #- uses: mxschmitt/action-tmate@v3
      - name: Build and test
        run: ./ci/build.sh
