name: main
on: [push]
env:
  CI_COMMIT: ${{ github.sha }}

  # Elastic Beanstalk environment to deploy to
  DEPLOY_ENV: agora-test-a

  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # SSH debugging
      #- uses: mxschmitt/action-tmate@v3
      - name: Build and test
        run: ./ci/build.sh
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Docker images
        run: ./ci/docker-push.sh

      # Build and push Docker image & Elastic Beanstalk bundle (skip for pull requests)
      - name: Build and Push Application
        if: github.event_name == 'push'
        run: |
          source ci/env.sh
          ./ci/eb-build.sh
          ./ci/eb-publish.sh

      # Deploy to Elastic Beanstalk (skip for pull requests)
      - name: Deploy to Elastic Beanstalk
        if: github.event_name == 'push'
        run: source ci/env.sh && ./ci/eb-deploy.sh "$DEPLOY_ENV"
