name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: docker run --rm -v "$(pwd)/client:/code" --workdir /code --user node node:16.15.0-bullseye-slim bash -c 'npm ci && npm run build'
